import type { Metadata } from 'next';
import './globals.css';
import { 
  karla,
  anaheim,
  barlowLight,
  barlowRegular,
  barlowMedium
} from '@style/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${
          barlowMedium.className
        } antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
