name: Next CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.x, 21.x, 22.x]

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --dev

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present
